In [22]:
from PIL import Image
import numpy as np
import skimage
import skimage.io
import skimage.feature
from skimage.feature import greycoprops
from skimage.transform import resize
import math
import statistics
import scipy
import scipy.stats
from scipy.stats import skew
from decimal import Decimal
from PIL import Image 
from scipy import misc
from numpy import genfromtxt
import matplotlib.pyplot as plt
import os
from sklearn.metrics import confusion_matrix
from sklearn.metrics import plot_confusion_matrix

In [23]:
train_feature = []
train_label = []
test_feature = []
test_label = []

In [24]:
root_train = 'C:/Kuliah/Semester VII/Tes Dataset/chest_xray/chest_xray/train'
root_test = 'C:/Kuliah/Semester VII/Tes Dataset/chest_xray/chest_xray/test'

In [25]:
def train(parent):
    print("Training started!")

    folder_index = 0
    image_index = 0
    image_total = 0

    feature = []
    label = []
    index = 0

    for folder in os.listdir(parent):
        
        current_path = "".join((parent, "/", folder))

        print("Extracting Feature from", folder)

        for file in os.listdir(current_path):
            path = (current_path + "/" + file)
            print(path)

            img = skimage.io.imread(path, as_gray=True)
            img = resize(img,(300,300))
            img = skimage.img_as_ubyte(img)
            img = np.asarray(img, dtype="int32")
            
            g = skimage.feature.greycomatrix(img, [1], [np.pi/4], levels=img.max()+1, symmetric=False, normed=True)
            glcm_contrast = skimage.feature.greycoprops(g, 'contrast')[0][0]
            glcm_energy = skimage.feature.greycoprops(g, 'energy')[0][0]
            glcm_homogeneity = skimage.feature.greycoprops(g, 'homogeneity')[0][0]
            glcm_correlation = skimage.feature.greycoprops(g, 'correlation')[0][0]

            if not glcm_contrast is None or not glcm_energy is None or not glcm_homogeneity is None or not glcm_correlation is None:
                temp = [glcm_contrast, glcm_energy, glcm_homogeneity, glcm_correlation,index]
                print(temp)
                train_feature.append(temp)
                train_label.append(index)
        np.savetxt("LVQ-GLCM-45_train_feature.csv", train_feature, delimiter=",")
        index = index + 1
    print("Training finish...")

In [26]:
def test(parent):
    print("Testing started!")
    folder_index = 0
    image_index = 0
    image_total = 0

    feature = []
    label = []
    index = 0

    for folder in os.listdir(parent):
        
        current_path = "".join((parent, "/", folder))

        print("Extracting Feature from", folder)

        for file in os.listdir(current_path):
            path = (current_path + "/" + file)

            img = skimage.io.imread(path, as_gray=True)
            img = resize(img,(300,300))
            img = skimage.img_as_ubyte(img)
            img = np.asarray(img, dtype="int32")

            g = skimage.feature.greycomatrix(img, [1], [np.pi/4], levels=img.max()+1, symmetric=False, normed=True)
            glcm_contrast = skimage.feature.greycoprops(g, 'contrast')[0][0]
            glcm_energy = skimage.feature.greycoprops(g, 'energy')[0][0]
            glcm_homogeneity = skimage.feature.greycoprops(g, 'homogeneity')[0][0]
            glcm_correlation = skimage.feature.greycoprops(g, 'correlation')[0][0]

            if not glcm_contrast is None or not glcm_energy is None or not glcm_homogeneity is None or not glcm_correlation is None:
                temp = [glcm_contrast, glcm_energy, glcm_homogeneity, glcm_correlation,index]
                # print(temp)
                test_feature.append(temp)
                test_label.append(index)
        np.savetxt("LVQ-GLCM-45_test_feature.csv", test_feature, delimiter=",")
        index = index + 1
    print("Testing finish...")

In [27]:
def main():
     X_train = genfromtxt('C:\\Kuliah\\Semester VII\\Tes Dataset\\LVQ-GLCM-45_train_feature.csv', delimiter=',')
     X_train = np.nan_to_num(np.array(X_train))

     X_test = genfromtxt('C:\\Kuliah\\Semester VII\\Tes Dataset\\LVQ-GLCM-45_test_feature.csv', delimiter=',')
     X_test = np.nan_to_num(np.array(X_test))

train(root_train)
test(root_test)

X_train = np.nan_to_num(np.array(train_feature))
X_test = np.nan_to_num(np.array(test_feature))

print("\nTraining Features\n")
print("Training features with dimension:", X_train.shape)

print("\nTest Features\n")
print("Test features with dimension:", X_test.shape)
main()

]
C:/Kuliah/Semester VII/Tes Dataset/chest_xray/chest_xray/train/PNEUMONIA/person659_virus_1243.jpeg
[80.38530888916233, 0.06290786312464623, 0.3228918969787831, 0.9899801872346427, 1]
C:/Kuliah/Semester VII/Tes Dataset/chest_xray/chest_xray/train/PNEUMONIA/person65_bacteria_322.jpeg
[21.00681200433999, 0.03338002858037876, 0.33805388023762184, 0.9865148126551474, 1]
C:/Kuliah/Semester VII/Tes Dataset/chest_xray/chest_xray/train/PNEUMONIA/person660_virus_1244.jpeg
[86.22752541917878, 0.09347538066350232, 0.3344075836521585, 0.9903685697653942, 1]
C:/Kuliah/Semester VII/Tes Dataset/chest_xray/chest_xray/train/PNEUMONIA/person661_virus_1245.jpeg
[63.00533551078846, 0.029784173244924397, 0.27126504249957395, 0.9879223427268187, 1]
C:/Kuliah/Semester VII/Tes Dataset/chest_xray/chest_xray/train/PNEUMONIA/person662_virus_1246.jpeg
[50.18988601917205, 0.03351023994675526, 0.3365676673334015, 0.9904814131075043, 1]
C:/Kuliah/Semester VII/Tes Dataset/chest_xray/chest_xray/train/PNEUMONIA/person

In [28]:
# LVQ for the Ionosphere Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt

In [29]:
def load_csv(filename):
	dataset = list()
	with open(filename, 'r') as file:
		csv_reader = reader(file)
		for row in csv_reader:
			if not row:
				continue
			dataset.append(row)
	return dataset

In [30]:
def str_column_to_float(dataset, column):
	for row in dataset:
		row[column] = float(row[column].strip())

In [31]:
def str_column_to_int(dataset, column):
	class_values = [row[column] for row in dataset]
	unique = set(class_values)
	lookup = dict()
	for i, value in enumerate(unique):
		lookup[value] = i
	for row in dataset:
		row[column] = lookup[row[column]]
	return lookup

In [32]:
def cross_validation_split(dataset, n_folds):
	dataset_split = list()
	dataset_copy = list(dataset)
	fold_size = int(len(dataset) / n_folds)
	for i in range(n_folds):
		fold = list()
		while len(fold) < fold_size:
			index = randrange(len(dataset_copy))
			fold.append(dataset_copy.pop(index))
		dataset_split.append(fold)
	return dataset_split

In [33]:
def accuracy_metric(actual, predicted):
	correct = 0
	for i in range(len(actual)):
		if actual[i] == predicted[i]:
			correct += 1
	return correct / float(len(actual)) * 100.0

In [34]:
def evaluate_algorithm(dataset, algorithm, n_folds, *args):
	folds = cross_validation_split(dataset, n_folds)
	scores = list()
	for fold in folds:
		train_set = list(folds)
		train_set.remove(fold)
		train_set = sum(train_set, [])
		test_set = list()
		for row in fold:
			row_copy = list(row)
			test_set.append(row_copy)
			row_copy[-1] = None
		predicted = algorithm(train_set, test_set, *args)
		actual = [row[-1] for row in fold]
		cm = confusion_matrix(actual, predicted)
		print(cm)
		accuracy = accuracy_metric(actual, predicted)
		scores.append(accuracy)
	return scores

In [35]:
def euclidean_distance(row1, row2):
	distance = 0.0
	for i in range(len(row1)-1):
		distance += (row1[i] - row2[i])**2
	return sqrt(distance)

In [36]:
def get_best_matching_unit(codebooks, test_row):
	distances = list()
	for codebook in codebooks:
		dist = euclidean_distance(codebook, test_row)
		distances.append((codebook, dist))
	distances.sort(key=lambda tup: tup[1])
	return distances[0][0]

In [37]:
def predict(codebooks, test_row):
	bmu = get_best_matching_unit(codebooks, test_row)
	return bmu[-1]

In [38]:
def random_codebook(train):
	n_records = len(train)
	n_features = len(train[0])
	codebook = [train[randrange(n_records)][i] for i in range(n_features)]
	return codebook

In [39]:
def train_codebooks(train, n_codebooks, lrate, epochs):
	codebooks = [random_codebook(train) for i in range(n_codebooks)]
	for epoch in range(epochs):
		rate = lrate * (1.0-(epoch/float(epochs)))
		for row in train:
			bmu = get_best_matching_unit(codebooks, row)
			for i in range(len(row)-1):
				error = row[i] - bmu[i]
				if bmu[-1] == row[-1]:
					bmu[i] += rate * error
				else:
					bmu[i] -= rate * error
	return codebooks

In [40]:
def learning_vector_quantization(train, test, n_codebooks, lrate, epochs):
	codebooks = train_codebooks(train, n_codebooks, lrate, epochs)
	predictions = list()
	for row in test:
		output = predict(codebooks, row)
		predictions.append(output)
	return(predictions)

In [41]:
seed(1)

In [43]:
# load and prepare data
filename = 'LVQ-GLCM-45_test_feature.csv'
dataset = load_csv(filename)
for i in range(len(dataset[0])-1):	
	str_column_to_float(dataset, i)
# convert class column to integers
str_column_to_int(dataset, len(dataset[0])-1)
# evaluate algorithm
n_folds = 5
learn_rate = 0.4
n_epochs = 200
n_codebooks = 20
scores = evaluate_algorithm(dataset, learning_vector_quantization, n_folds, n_codebooks, learn_rate, n_epochs)
print('Scores: %s' % scores)
print('Mean Accuracy: %.3f%%' % (sum(scores)/float(len(scores))))

[[30 13]
 [ 8 29]]
[[25 11]
 [ 7 37]]
[[23 25]
 [ 4 28]]
[[31  7]
 [16 26]]
[[22 13]
 [13 32]]
Scores: [73.75, 77.5, 63.74999999999999, 71.25, 67.5]
Mean Accuracy: 70.750%
